language: node_js

sudo: false

node_js:
- 12

script:
- |
    npm run $TEST_TYPE
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=test
  - TEST_TYPE=coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION